[package]
name = "jwt"
version = "1.1.0"
authors = ["Alex Maslakov <me@gildedhonour.com>, <gilded.honour@gmail.com>"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/GildedHonour/rust-jwt"
repository = "https://github.com/GildedHonour/rust-jwt"
description = "Implementation of JSON JWT"
keywords = ["Crypto", "JWT", "JSON", "JSON Web token", "jwt.io"]
readme = "README.md"

[dependencies]
rust-crypto = "*"
rustc-serialize = "0.3.15"
time = "0.1.26"

[lib]
name = "jwt"