[package]
name = "jwt-rust"
version = "0.0.1"
authors = ["Alex Maslakov <me@gildedhonour.com>"]

[lib]
name = "jwt-rust"

[dependencies]
rust-crypto = "*"

[dependencies.time]
git = "https://github.com/rust-lang/time"