[package]
name = "rust-jwt"
version = "0.1.0"
authors = ["Alex Maslakov <me@gildedhonour.com>, <gilded.honour@gmail.com>"]
license = "GNU GPL v3.0"
homepage = "https://github.com/GildedHonour/rust-jwt"
repository = "https://github.com/GildedHonour/rust-jwt"
description = "Implementation of JSON JWT"
keywords = ["Crypto", "JWT", "JSON", "JSON Web token", "jwt.io"]
readme = "README.md"

[dependencies]
rust-crypto = "*"

[dependencies.time]
git = "https://github.com/rust-lang/time"

[lib]
name = "rust-jwt"
path = "src/jwt.rs"